[[[Н‘Документация по языку программирования 11l’]]]
[[[Правила определения областей/]]]‘Блоки кода’[./code-blocks]

‘[[[Грамматика без точки]]]Точка с запятой и автоматическое склеивание строк’[./semicolons]

Комментарии[./comments]

‘Строковые литералы’[./string-literals]
‘Целочисленные литералы’[./integer-literals]

Зарезервированные/ключевые слова:
   A/var[./A]
   C/in[./C]
‘   I/if и E/else’[./I]
   F/fn[./F]
   L/loop[./L]
   N/null[./N]
   R/return[./R]
   S/switch[./S]
   T/type[./T]
   X/exception[./X]

‘Встроенные типы данных’[./built-in-types]

Операторы[./operators]

‘Префиксы переменных’[./prefixes]

‘[[[Глобальные/]]]Встроенные функции’[./built-in-functions]

Встроенные модули:
   os[./built-in-modules/os]
   fs[./built-in-modules/fs]
