[[[Н‘Документация по языку программирования 11l’]]]
[[[Правила определения областей/]]]‘Блоки кода’[./code-blocks]

‘Грамматика без точки с запятой и автоматическое склеивание строк’[./semicolons]

Комментарии[./comments]

Зарезервированные/ключевые слова:
   A/var[./A]
‘   I/if и E/else’[./I]
   C/in[./C]
   F/fn[./F]
   L/loop[./L]
   N/null[./N]
   R/return[./R]
   S/switch[./S]
   T/type[./T]
   X/exception[./X]

‘Встроенные типы данных’[./built-in-types]

Операторы[./operators]

‘Глобальные функции’[./global-functions]

Встроенные модули:
   os[./modules/os]
   fs[./modules/fs]
