[[[H‘11l Documentation’]]]
[[[Scoping rules/]]]‘Code blocks’[./code-blocks]

‘Semicolon free grammar and implied line joining’[./semicolons]

Comments[./comments]

‘String literals’[./string-literals]
‘Integer literals’[./integer-literals]

Keywords:
   C/in[./C]
‘   I/if and E/else’[./I]
   F/fn[./F]
   L/loop[./L]
   N/null[./N]
   R/return[./R]
   S/switch[./S]
   T/type[./T]
   V/var[./V]
   X/exception[./X]

‘Built-in types’[./built-in-types]

Operators[./operators]

‘Variables' prefixes’[./prefixes]

‘[[[Global/]]]Built-in Functions’[./built-in-functions]

Built-in modules:
   os[./built-in-modules/os]
   fs[./built-in-modules/fs]
   time[./built-in-modules/time]
   re[./built-in-modules/re]
   random[./built-in-modules/random]
   ‘minheap and maxheap’[./built-in-modules/minmaxheap]
