[[[H‘11l Documentation’]]]
[[[Scoping rules/]]]‘Code blocks’[./code-blocks]

‘Semicolon free grammar and implied line joining’[./semicolons]

Comments[./comments]

Keywords:
   A/var[./A]
‘   I/if and E/else’[./I]
   C/in[./C]
   F/fn[./F]
   L/loop[./L]
   N/null[./N]
   R/return[./R]
   S/switch[./S]
   T/type[./T]
   X/exception[./X]

‘Built-in types’[./built-in-types]

Operators[./operators]

‘Global functions’[./global-functions]

Built-in modules:
   os[./modules/os]
   fs[./modules/fs]
