[[[H‘Integer literals’
]]]H‘Integer literals’

[[[Inspired by ‘this page’[https://trizen.gitbooks.io/sidef-lang/content/programming_tasks/L/Literals/Integer.html]]]]
#(11l)‘
print(255)        // decimal literal
print(0000'00FF)  // hexadecimal literal
print(00'FF)      // short hexadecimal literal
print(377o)       // octal literal
print(1111'1111b) // binary literal
’
Output:
`
255
255
255
255
255
`

Note that digit separator `'` is necessary [[[only ]]]for hexadecimal literals.
